#
# Module manifest for module 'BicepConsoleTTK'
#
# Generated by: Andrew Wilson
#
# Generated on: 17/05/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'BicepConsoleTTK.psm1'

# Version number of this module.
ModuleVersion = '0.2.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '3d89c72d-c69e-47ad-8f50-d2fd9b536505'

# Author of this module
Author = 'Andrew Wilson'

# Company or vendor of this module
CompanyName = 'Andrew Wilson'

# Copyright statement for this module
Copyright = '(c) Andrew Wilson. MIT License.'

# Description of the functionality provided by this module
Description = 'Bicep Console Test Tool Kit (BicepConsoleTTK) — test Bicep imported types, functions and variables via the Bicep Console REPL using Pester'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Import-Bicep', 'Invoke-BicepExpression', 'ConvertTo-BicepConsoleResult', 'ConvertTo-BicepLiteral'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Bicep', 'Azure', 'Testing', 'Pester'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Andrew-D-Wilson/bicep-console-test-framework/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Andrew-D-Wilson/bicep-console-test-framework'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '## 0.2.0-pre (2026-05-17)

### New Features
- Added ConvertTo-BicepConsoleResult: converts a PowerShell null, bool, number, string, [ordered]@{}, [pscustomobject], or array to the exact string that Invoke-BicepExpression returns for an equivalent Bicep value, enabling clean Should -Be assertions without hand-crafting multi-line escape sequences
- Added ConvertTo-BicepLiteral: converts a PowerShell value to a Bicep literal expression string (the value portion after =). Use it inside a PS subexpression when building SetupDeclarations so complex typed values can be written as structured PowerShell data rather than hand-crafted single-line strings. Shares the same Format-BicepValue private helper as ConvertTo-BicepConsoleResult — output format is identical

## 0.1.1 (2026-05-09)

### Bug Fixes
- Fixed multi-line object literal bodies in func declarations being collapsed without commas between properties, causing a Bicep console parse error (e.g. `func generateBaseTags` using `union(origTags, { ... })`)
- Fixed array type aliases (e.g. `type Foo = Bar[]`) being emitted before their element type when imported by name, causing a "not a valid type" error in the Bicep console. Import-Bicep now resolves and emits element type dependencies first.

## 0.1.0 (2026-05-08)

Initial release of BicepConsoleTTK (Bicep Console Test Tool Kit).

### Features
- Import-Bicep: parse named and wildcard import statements to extract exported func, type and var declarations from Bicep files
- Invoke-BicepExpression: evaluate a Bicep expression via the bicep console REPL and return the result for Pester assertions
- Multi-file imports with preserved declaration order
- Automatic deduplication of imported members
- SetupDeclarations support for pre-declaring typed variables before the test expression
- Pipeline input support for Import-Bicep
- Clear error messages: Bicep console errors are caught, tilde/caret noise stripped, and re-thrown as readable exceptions
- 30-second process timeout to prevent CI pipeline hangs
- Compatible with Windows PowerShell 5.1 (Desktop) and PowerShell 7+ (Core)'

        # Prerelease string of this module
        Prerelease = 'Prerelease'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

